server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true
  devtools:
    livereload:
      enabled: true
spring:
  profiles:
    active: prod #Oracle
#    active: dev #MySQL
